In [57]:
import torch

In [58]:
x = torch.arange(4.0, requires_grad=True)
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [59]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [60]:
y.backward()

In [61]:
x.grad == 4 * x

tensor([True, True, True, True])

In [62]:
x.grad.zero_()

tensor([0., 0., 0., 0.])

In [63]:
y = x.sum()
y

tensor(6., grad_fn=<SumBackward0>)

In [64]:
y.backward()

In [65]:
x.grad

tensor([1., 1., 1., 1.])

In [66]:
torch.sum(x)

tensor(6., grad_fn=<SumBackward0>)

In [67]:
help(torch.ones)

Help on built-in function ones in module torch:

ones(...)
    ones(*size, *, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) -> Tensor

    Returns a tensor filled with the scalar value `1`, with the shape defined
    by the variable argument :attr:`size`.

    Args:
        size (int...): a sequence of integers defining the shape of the output tensor.
            Can be a variable number of arguments or a collection like a list or tuple.

    Keyword arguments:
        out (Tensor, optional): the output tensor.
        dtype (:class:`torch.dtype`, optional): the desired data type of returned tensor.
            Default: if ``None``, uses a global default (see :func:`torch.set_default_dtype`).
        layout (:class:`torch.layout`, optional): the desired layout of returned Tensor.
            Default: ``torch.strided``.
        device (:class:`torch.device`, optional): the desired device of returned tensor.
            Default: if ``None``, uses the curre