In [29]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

In [30]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

In [31]:
layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [32]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

In [33]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-5.5879e-09, grad_fn=<MeanBackward0>)

In [34]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

In [35]:
linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-1.2375,  1.0519,  0.2189],
        [ 0.5860,  0.3551,  0.2080],
        [-0.3727, -0.4566,  0.1454],
        [-0.9962,  1.9057,  1.1795],
        [-0.5687,  1.7771,  0.4563]], requires_grad=True)

In [36]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.6860, 2.1827],
        [0.0000, 0.0277, 2.2318]])

In [37]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.0000],
        [2.3462]])